version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: weather_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5543:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql